# Generated by Django 4.0.4 on 2022-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=255)),
                ('PROJECT_NAME', models.CharField(max_length=255)),
                ('PROJECT_NO', models.CharField(max_length=255)),
                ('OLD_PROJECT_NO', models.CharField(max_length=255)),
            ],
        ),
    ]
