# Generated by Django 4.0.4 on 2022-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_sheet', '0003_alter_kayaroganam_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayaroganam',
            name='server_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
